export const ADDED = "todo/added"
export const TOGGLE = "todo/toggle"
export const COLORSELECTED = "todo/colorselected"
export const DELETED = "todo/deleted"
export const ALLCOMPLETED = "todo/allcompleted"
export const CLEARCOMPLETED = "todo/clearcompleted"